# Generated by Django 4.0.5 on 2022-06-22 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='choices',
            new_name='user_owner',
        ),
    ]
