# Generated by Django 4.0.5 on 2022-06-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='currency',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
